### ISSUE TITLE
使用你脚本移植是这样

### ISSUE THREAD

**Issue by zhoubonet** [ruizhipeng/kubernetes-redis-cluster#1]
>>> Nodes configuration updated
>>> Assign a different config epoch to each node
>>> Sending CLUSTER MEET messages to join the cluster
Waiting for the cluster to join...............................................................................................................................................................................................................................................................................................................................................................

**Comment by planktonzp** [comment]
你用的是哪个版本的yaml啊

**Comment by planktonzp** [comment]
现在测试的方式是选用debug3
然后通过外部命令来发起集群建立请求 来避免重启时重复建立集群引起问题

**Comment by zhoubonet** [comment]
恩，我试试

**Comment by zhoubonet** [comment]
你现在使用的脚本还是debug3吗？有更新吗？？？

**Comment by planktonzp** [comment]
有什么问题么  最近在做1.8的一键部署没有做这方面 如果有什么问题的话可以反馈在这 我会更新修复的
